apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: book
spec:
  replicas: 5
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: dev-book
        image: 257070983248.dkr.ecr.us-east-1.amazonaws.com/dev-book:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: utrains-service
spec:
  type: LoadBalancer
  selector:
    app: books
  ports:
    - port: 80
      targetPort: 8
